# Generated by Django 6.0.2 on 2026-07-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_order_address'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
