# Generated by Django 6.0.2 on 2026-03-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_owner_store_seller'),
        ('products', '0024_remove_product_products_seller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
