# Generated by Django 5.2.10 on 2026-06-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_delete_seller_brand_user'),
        ('products', '0028_remove_product_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
