# Generated by Django 6.0 on 2026-02-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Beverages', 'Beverages'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Grocery', 'Grocery'), ('Households', 'Households'), ('Personal Care', 'Personal Care'), ('Others', 'Others')], default='Others'),
        ),
    ]
