# Generated by Django 6.0 on 2026-02-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Beverages', 'Beverages'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Grocery', 'Grocery'), ('Others', 'Others')], default='Others'),
        ),
    ]
