# Generated by Django 6.0 on 2026-02-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Beverages', 'Beverages'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Grocery', 'Grocery'), ('Personal Care', 'Personal Care'), ('Snacks', 'Snacks'), ('Stationary', 'Stationary'), ('Others', 'Others')], default='Others'),
        ),
    ]
