# Generated by Django 5.2.10 on 2026-03-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_id_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
