# Generated by Django 6.0.2 on 2026-03-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='products/default-image.jpg', null=True, upload_to='products/'),
        ),
    ]
