# Generated by Django 6.0.2 on 2026-03-15 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('products', '0021_product_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.store'),
        ),
    ]
