# Generated by Django 6.0.2 on 2026-03-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_seller',
            new_name='products_seller',
        ),
    ]
