# Generated by Django 6.0.2 on 2026-03-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_rename_product_seller_product_products_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='products_seller',
        ),
    ]
