# Generated by Django 6.0.2 on 2026-03-16 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_initial'),
        ('products', '0024_remove_product_products_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.seller'),
        ),
    ]
