# Generated by Django 6.0.2 on 2026-03-16 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_brand'),
        ('products', '0025_product_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_seller',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.brand'),
        ),
    ]
