# Generated by Django 6.0.2 on 2026-06-01 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_remove_product_product_seller_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='products_tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
