# Generated by Django 5.2.10 on 2026-06-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_products_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
